# Generated by Django 3.0.7 on 2020-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao_curta', models.TextField(max_length=255)),
                ('descricao_longa', models.TextField()),
                ('imagem', models.ImageField(upload_to='produto_imagens/%Y/%m/', blank=True, null=True)),
                ('slug', models.SlugField(unique=True, blank=True, null=True)),
                ('preco_marketing', models.FloatField(verbose_name='Preço')),
                ('preco_marketing_promocional', models.FloatField(default=0, verbose_name='Preço Promo.')),
                ('tipo', models.CharField(
                    default='V',
                    max_length=1,
                    choices=(
                        ('V', 'Variável'),
                        ('S', 'Simples'),
                    )
                )),
            ],
        ),
    ]
